curveball-2014.12.19 release

diff --git a/src/packaging/make-deb b/src/packaging/make-deb
--- a/src/packaging/make-deb
+++ b/src/packaging/make-deb
@@ -17,7 +17,7 @@
 # implied.  See the License for the specific language governing
 # permissions and limitations under the License.
 
-THISDIR=$(dirname "$0")
+THISDIR=$(/usr/bin/dirname $(/usr/bin/which "$0"))
 
 SHORTNAME=curveball
 TARGETDIR=/opt/"${SHORTNAME}"
@@ -36,11 +36,16 @@ error() { log "ERROR: $*" >&2; }
 fatal() { error "$*"; exit 1; }
 usage_fatal() { error "$*"; usage >&2; exit 1; }
 
+# Use create-version directory; use create-version
+# to make a date-based string that makes sense for exports.
+#
+VERSION=$("${THISDIR}"/create-version)
+
 # The VERSION file must contain only the version string and nothing else.
-VERSION=$(cat "${THISDIR}"/VERSION | head -1 | awk '{print $1}')
-if [ $? -ne 0 ]; then
-    fatal "Cannot access VERSION file"
-fi
+# VERSION=$(cat "${THISDIR}"/VERSION | head -1 | awk '{print $1}')
+# if [ $? -ne 0 ]; then
+#     fatal "Cannot access VERSION file"
+# fi
 
 ARCHITECTURE=$(dpkg --print-architecture)
 
@@ -51,14 +56,12 @@ ARCHITECTURE=$(dpkg --print-architecture)
 
 remove_bloat() {
 
-    UNNEEDED="sentinels/keys"
+    UNNEEDED="bbn-tools sentinels"
 
     for bloat in ${UNNEEDED}; do
 	target="${INSTALLDIR}/${bloat}"
 	if [ -e "${target}" ]; then
 	    rm -rf "${target}"
-	else
-	    log "unneeded file" "${target}" "already removed"
 	fi
     done
 
@@ -71,8 +74,6 @@ remove_bloat() {
     rm -rf "${INSTALLDIR}"/experiments/out
     rm -rf "${INSTALLDIR}"/out
     rm -rf "${INSTALLDIR}"/scripts/out
-    rm -rf "${INSTALLDIR}"/sentinels/out
-    rm -rf "${INSTALLDIR}"/sentinels/sdata
 
     return 0
 }
@@ -130,6 +131,34 @@ add_click() {
     rm -rf "${INSTALLDIR}"/click/curveball/.tmp_versions
 }
 
+# Copy the installed version of the "Curveball" click from
+# /opt/curveball/click-inst to the staging area.
+#
+add_click_inst() {
+
+    if [ ! -d /opt/curveball/click-inst ]; then
+	fatal "Cannot find installed click in /opt/curveball"
+    fi
+
+    (cd /opt/curveball/ ; tar cf - click-inst) | \
+	    (cd "${INSTALLDIR}" ; tar xf -)
+
+    # Prune out the executables we don't need
+    for f in click-devirtualize click-pretty click-fastclassifier \
+	    click-align xml2click click-xform click-combine \
+	    click-mkmindriver click-uncombine click-flatten \
+	    click-buildtool click-compile click-mkelemmap \
+	    click2xml click-check click-elem2man click-undead ; do
+	rm -f "${INSTALLDIR}/click-inst/bin/$f"
+    done
+
+    # Prune out the static libraries we've already linked against
+    for f in libclick.a libclicktool.a ; do
+	rm -f "${INSTALLDIR}/click-inst/lib/$f"
+    done
+
+}
+
 # Clean up after earlier builds
 if [ -e "${SCRATCHDIR}" ]; then
     /bin/rm -rf "${SCRATCHDIR}"
@@ -168,8 +197,8 @@ Version: ${VERSION}
 Section: base
 Priority: optional
 Architecture: ${ARCHITECTURE}
-Maintainer: Raytheon / BBN Technologies
-Description: Curveball release
+Maintainer: Raytheon BBN Technologies
+Description: BBN Curveball release
 EOF
 
 cat "${DEBDIR}"/control
@@ -183,8 +212,8 @@ Depends: \
 	libtk-img, tcl, tk, tsocks, proxychains, \
 	libnetfilter-queue1, nmap, python-pyside, \
 	zlib1g-dev, python-bitarray, python-pexpect, \
-	curl, debsums, python-tlslite, ethtool, \
-	python-socksipy
+	curl, debsums, python-tlslite, ethtool, libpcap0.8-dev, \
+	python-socksipy, python-pcapy, python-netifaces, python-dnspython
 EOF
 
 cat >> "${DEBDIR}"/postinst << EOF
@@ -223,7 +252,7 @@ fi
 config_tsocks
 config_proxychains
 
-echo "DO NOT FORGET TO BUILD CLICK FOR THE DR"
+# echo "DO NOT FORGET TO BUILD CLICK FOR THE DR"
 # cd $TARGETDIR/click ; sudo make install || exit 1
 
 case \$(hostname -f) in
@@ -248,6 +277,8 @@ cat >> "${DEBDIR}"/prerm << EOF
 # pre remove for ${SHORTNAME} ${VERSION}
 
 /bin/rm -rf "${TARGETDIR}/click/"*
+/bin/rm -rf "${TARGETDIR}/click-inst"
+/bin/rm -rf "${TARGETDIR}/scripts/"*.log "${TARGETDIR}/scripts/"*.log.?
 
 exit 0
 EOF
@@ -283,7 +314,8 @@ EOF
     chmod 755 "${DEBDIR}"/preinst
 }
 
-add_click
+# add_click
+add_click_inst
 remove_bloat
 add_build_info
 add_docs
@@ -299,8 +331,17 @@ find "${INSTALLDIR}/python" -type f | xargs chmod 0644
 find "${INSTALLDIR}/lib" -type f | xargs chmod 0644
 find "${INSTALLDIR}/scripts" -executable | xargs chmod 0755
 find "${INSTALLDIR}/test" -executable | xargs chmod 0755
-find "${INSTALLDIR}" -perm 0664 | xargs chmod 0644
-find "${INSTALLDIR}" -perm 0775 | xargs chmod 0755
+
+# correct any permission issues (there shouldn't be any,
+# so check first)
+
+if [ $(find "${INSTALLDIR}" -perm 0664 | wc -l) -gt 0 ]; then
+    find "${INSTALLDIR}" -perm 0664 | xargs chmod 0644
+fi
+
+if [ $(find "${INSTALLDIR}" -perm 0775 | wc -l) -gt 0 ]; then
+    find "${INSTALLDIR}" -perm 0775 | xargs chmod 0755
+fi
 
 /usr/bin/fakeroot dpkg-deb --build "${SCRATCHDIR}" || fatal dpkg-deb failed
 
diff --git a/src/test/latency b/src/test/latency
--- a/src/test/latency
+++ b/src/test/latency
@@ -64,7 +64,7 @@ ECHOPORT=2300
 #
 unset http_proxy
 
-CLIENT=client.py
+CLIENT=curveball-client
 CLIENTPATH="${SCRIPTDIR}/${CLIENT}"
 ECHOCLIENT="${DIRNAME}/echo-client"
 
@@ -73,99 +73,219 @@ PKILL=/usr/bin/pkill
 
 NC=/bin/nc
 
-CNT=0
-STARTTIME=$(/bin/date +"%s.%N")
-while [ $CNT -lt $ITERS ]; do
-    CNT=$((CNT + 1))
-    echo 'hi' | ${ECHOCLIENT} ${COVERT} ${ECHOPORT} > /dev/null
+usage() {
+    cat <<.
+
+    $0: run a latency test for the given tunnel
+
+    Each test specified on the commandline is run once.
+    Tests may be specified by test number or name.
+
+    Num Name               Description
+
+    0  all                 Run all of the test conditions
+    1  normal              Ordinary (tcp)
+    2  curveball-http      Curveball http
+    3  curveball-https     Curveball https
+    4  curveball-http-uni  Curveball http-uni
+    5  curveball-tls-uni   Curveball tls-uni
+
+.
+}
+
+if [ $# -eq 0 ]; then
+    usage
+    exit 1
+fi
+
+DO_NORMAL=0
+DO_CURVEBALL_HTTP=0
+DO_CURVEBALL_HTTPS=0
+DO_CURVEBALL_HTTP_UNI=0
+DO_CURVEBALL_TLS_UNI=0
+
+for testcase in $* ; do
+    case "$testcase" in
+	1|normal)
+	    DO_NORMAL=1
+	    ;;
+	2|curveball-http)
+	    DO_CURVEBALL_HTTP=1
+	    ;;
+	3|curveball-https)
+	    DO_CURVEBALL_HTTPS=1
+	    ;;
+	4|curveball-http-uni)
+	    DO_CURVEBALL_HTTP_UNI=1
+	    ;;
+	5|curveball-tls-uni)
+	    DO_CURVEBALL_TLS_UNI=1
+	    ;;
+	0|all)
+	    DO_NORMAL=1
+	    DO_CURVEBALL_HTTP=1
+	    DO_CURVEBALL_HTTPS=1
+	    DO_CURVEBALL_HTTP_UNI=1
+	    DO_CURVEBALL_TLS_UNI=1
+	    ;;
+	-h|help)
+	    usage
+	    exit 0
+	    ;;
+	*)
+	    echo "$0: Error: Unknown test condition $testcase"
+	    usage
+	    exit 1
+	    ;;
+    esac
 done
-ENDTIME=$(/bin/date +"%s.%N")
 
-RTT=$(echo "($ENDTIME - $STARTTIME) / $ITERS" | bc -l)
-echo "normal echo TtFB $RTT"
 
-STARTTIME=$(/bin/date +"%s.%N")
-echo 'hi' | ${ECHOCLIENT} -n ${ITERS} -q ${COVERT} ${ECHOPORT}
-ENDTIME=$(/bin/date +"%s.%N")
+if [ 0 -ne ${DO_NORMAL} ]; then
+    NITERS=$ITERS
 
-RTT=$(echo "($ENDTIME - $STARTTIME) / $ITERS" | bc -l)
-echo "normal echo RTT $RTT"
+    CNT=0
+    STARTTIME=$(/bin/date +"%s.%N")
+    while [ $CNT -lt $NITERS ]; do
+	CNT=$((CNT + 1))
+	echo 'hi' | ${ECHOCLIENT} ${COVERT} ${ECHOPORT} > /dev/null
+    done
+    ENDTIME=$(/bin/date +"%s.%N")
 
-# If there's already a curveball client running, then we don't know
-# what parameters it has: kill it and start a new one.
-#
-${SUDO} ${PKILL} -f ${CLIENT}
-${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w 2> /dev/null &
-sleep 5
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "normal echo TtFB $RTT"
 
-CNT=0
-STARTTIME=$(/bin/date +"%s.%N")
-while [ $CNT -lt $ITERS ]; do
-    CNT=$((CNT + 1))
-    echo 'hi' | ${ECHOCLIENT} -x localhost:5010 ${COVERT} ${ECHOPORT} > /dev/null
-done
-ENDTIME=$(/bin/date +"%s.%N")
+    STARTTIME=$(/bin/date +"%s.%N")
+    echo 'hi' | ${ECHOCLIENT} -n ${NITERS} -q ${COVERT} ${ECHOPORT}
+    ENDTIME=$(/bin/date +"%s.%N")
 
-RTT=$(echo "($ENDTIME - $STARTTIME) / $ITERS" | bc -l)
-echo "curveball-http echo TtFB $RTT"
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "normal echo RTT $RTT"
+fi
 
-STARTTIME=$(/bin/date +"%s.%N")
-echo 'hi' | ${ECHOCLIENT} -x localhost:5010 -n ${ITERS} -q ${COVERT} ${ECHOPORT}
-ENDTIME=$(/bin/date +"%s.%N")
+if [ 0 -ne ${DO_CURVEBALL_HTTP} ]; then
+    # Kill the Curveball client (if any) and restart in HTTP mode
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w 2> /dev/null &
+    sleep 5
 
-RTT=$(echo "($ENDTIME - $STARTTIME) / $ITERS" | bc -l)
-echo "curveball-http echo RTT $RTT"
+    NITERS=$ITERS
 
-# Kill the http client and rerun with the https client
-#
-${SUDO} ${PKILL} -f ${CLIENT}
-${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" 2> /dev/null &
-sleep 5
+    CNT=0
+    STARTTIME=$(/bin/date +"%s.%N")
+    while [ $CNT -lt $NITERS ]; do
+	CNT=$((CNT + 1))
+	echo 'hi' | ${ECHOCLIENT} -x localhost:5010 ${COVERT} ${ECHOPORT} > /dev/null
+    done
+    ENDTIME=$(/bin/date +"%s.%N")
 
-CNT=0
-STARTTIME=$(/bin/date +"%s.%N")
-while [ $CNT -lt $ITERS ]; do
-    CNT=$((CNT + 1))
-    echo 'hi' | ${ECHOCLIENT} -x localhost:5010 ${COVERT} ${ECHOPORT} > /dev/null
-done
-ENDTIME=$(/bin/date +"%s.%N")
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "curveball-http echo TtFB $RTT"
 
-RTT=$(echo "($ENDTIME - $STARTTIME) / $ITERS" | bc -l)
-echo "curveball-https echo TtFB $RTT"
+    STARTTIME=$(/bin/date +"%s.%N")
+    echo 'hi' | ${ECHOCLIENT} -x localhost:5010 -n ${NITERS} -q ${COVERT} ${ECHOPORT}
+    ENDTIME=$(/bin/date +"%s.%N")
 
-STARTTIME=$(/bin/date +"%s.%N")
-echo 'hi' | ${ECHOCLIENT} -x localhost:5010 -n ${ITERS} -q ${COVERT} ${ECHOPORT}
-ENDTIME=$(/bin/date +"%s.%N")
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "curveball-http echo RTT $RTT"
+fi
 
-RTT=$(echo "($ENDTIME - $STARTTIME) / $ITERS" | bc -l)
-echo "curveball-https echo RTT $RTT"
+if [ 0 -ne ${DO_CURVEBALL_HTTPS} ]; then
+    # Kill the Curveball client (if any) and restart in HTTPS mode
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" 2> /dev/null &
+    sleep 5
 
-# Kill the https client and rerun with the httpu client
-#
-# TODO: fix so that this reliably works.  Right now the messages are
-# too small to push through the system!
-#
-# ${SUDO} ${PKILL} -f ${CLIENT}
-# ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:8080" -w -u 2> /dev/null &
-# sleep 5
-#
-# CNT=0
-# STARTTIME=$(/bin/date +"%s.%N")
-# while [ $CNT -lt $ITERS ]; do
-    # CNT=$((CNT + 1))
-    # echo 'hi' | ${ECHOCLIENT} -x localhost:5010 ${COVERT} ${ECHOPORT} > /dev/null
-# done
-# ENDTIME=$(/bin/date +"%s.%N")
-#
-# RTT=$(echo "($ENDTIME - $STARTTIME) / $ITERS" | bc -l)
-# echo "curveball-httpu echo TtFB $RTT"
-#
-# STARTTIME=$(/bin/date +"%s.%N")
-# echo 'hi' | ${ECHOCLIENT} -x localhost:5010 -n ${ITERS} -q ${COVERT} ${ECHOPORT}
-# ENDTIME=$(/bin/date +"%s.%N")
-#
-# RTT=$(echo "($ENDTIME - $STARTTIME) / $ITERS" | bc -l)
-# echo "curveball-httpu echo RTT $RTT"
+    NITERS=$ITERS
+
+    CNT=0
+    STARTTIME=$(/bin/date +"%s.%N")
+    while [ $CNT -lt $NITERS ]; do
+	CNT=$((CNT + 1))
+	echo 'hi' | ${ECHOCLIENT} -x localhost:5010 ${COVERT} ${ECHOPORT} > /dev/null
+    done
+    ENDTIME=$(/bin/date +"%s.%N")
+
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "curveball-https echo TtFB $RTT"
+
+    STARTTIME=$(/bin/date +"%s.%N")
+    echo 'hi' | ${ECHOCLIENT} -x localhost:5010 -n ${NITERS} -q ${COVERT} ${ECHOPORT}
+    ENDTIME=$(/bin/date +"%s.%N")
+
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "curveball-https echo RTT $RTT"
+fi
+
+if [ 0 -ne ${DO_CURVEBALL_HTTP_UNI} ]; then
+    # Kill the Curveball client (if any) and restart in HTTP-UNI mode
+    #
+    # TODO: fix so that this reliably works.  Right now the messages are
+    # too small to push through the system!
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w -u 2> /dev/null &
+    sleep 5
+
+    # Use a very small number of iterations for HTTP-UNI because the
+    # latency is very large.
+    #
+    NITERS=50
+
+    CNT=0
+    STARTTIME=$(/bin/date +"%s.%N")
+    while [ $CNT -lt $NITERS ]; do
+	CNT=$((CNT + 1))
+	echo 'hi' | ${ECHOCLIENT} -x localhost:5010 ${COVERT} ${ECHOPORT} > /dev/null
+    done
+    ENDTIME=$(/bin/date +"%s.%N")
+
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "curveball-http-uni echo TtFB $RTT"
+
+    STARTTIME=$(/bin/date +"%s.%N")
+    echo 'hi' | ${ECHOCLIENT} -x localhost:5010 -n ${NITERS} -q ${COVERT} ${ECHOPORT}
+    ENDTIME=$(/bin/date +"%s.%N")
+
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "curveball-http-uni echo RTT $RTT"
+fi
+
+if [ 0 -ne ${DO_CURVEBALL_TLS_UNI} ]; then
+    # Kill the Curveball client (if any) and restart in TLS-UNI mode
+    #
+    # TODO: fix so that this reliably works.  Right now the messages are
+    # too small to push through the system!
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" -u 2> /dev/null &
+    sleep 5
+
+    # Use a very small number of iterations for TLS-UNI because the
+    # latency is very large.
+    #
+    NITERS=50
+
+    CNT=0
+    STARTTIME=$(/bin/date +"%s.%N")
+    while [ $CNT -lt $NITERS ]; do
+	CNT=$((CNT + 1))
+	echo 'hi' | ${ECHOCLIENT} -x localhost:5010 ${COVERT} ${ECHOPORT} > /dev/null
+    done
+    ENDTIME=$(/bin/date +"%s.%N")
+
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "curveball-http-uni echo TtFB $RTT"
+
+    STARTTIME=$(/bin/date +"%s.%N")
+    echo 'hi' | ${ECHOCLIENT} -x localhost:5010 -n ${NITERS} -q ${COVERT} ${ECHOPORT}
+    ENDTIME=$(/bin/date +"%s.%N")
+
+    RTT=$(echo "($ENDTIME - $STARTTIME) / $NITERS" | bc -l)
+    echo "curveball-tls-uni echo RTT $RTT"
+fi
 
 # Clean up any clients we left behind
 #
diff --git a/src/test/throughput b/src/test/throughput
--- a/src/test/throughput
+++ b/src/test/throughput
@@ -45,10 +45,15 @@ case ${EXPNAME} in
 	;;
 esac
 
-TSIZE=4000000
+TSIZE=1000000
+# The unidirectional client is much slower than the others,
+# so cut the transfer size so we don't have to wait forever.
+# TODO: use the same transfer size for http-uni.
+#
+SMALL_TSIZE=$((TSIZE / 2))
 ITERS=5
 
-CLIENT=client.py
+CLIENT=curveball-client
 CLIENTPATH="${SCRIPTDIR}/${CLIENT}"
 
 CURL=/usr/bin/curl
@@ -61,157 +66,300 @@ PKILL=/usr/bin/pkill
 #
 unset http_proxy
 
+usage() {
+    cat <<.
+
+    $0: run a throughput test for the given tunnel
+
+    Each test specified on the commandline is run once. 
+    Tests may be specified by test number or name.
+
+    Num Name                    Description
+
+    0  all                      Run all of the test conditions
+    1  normal-http              ordinary HTTP
+    2  normal-https             ordinary HTTPS
+    3  curveball-http-http      HTTP over Curveball http
+    4  curveball-http-https     HTTPS over Curveball http
+    5  curveball-https-http     HTTP over Curveball https
+    6  curveball-https-https    HTTPS over Curveball https
+    7  curveball-http-uni-http  HTTP over Curveball http-uni
+    8  curveball-http-uni-https HTTPS over Curveball http-uni
+    9  curveball-tls-uni-http   HTTP over Curveball tls-uni
+    10 curveball-tls-uni-https  HTTPS over Curveball tls-uni
+
+.
+}
+
+if [ $# -eq 0 ]; then
+    usage
+    exit 1
+fi
+
+DO_NORMAL_HTTP=0
+DO_NORMAL_HTTPS=0
+DO_CURVEBALL_HTTP_HTTP=0
+DO_CURVEBALL_HTTP_HTTPS=0
+DO_CURVEBALL_HTTPS_HTTP=0
+DO_CURVEBALL_HTTPS_HTTPS=0
+DO_CURVEBALL_HTTP_UNI_HTTP=0
+DO_CURVEBALL_HTTP_UNI_HTTPS=0
+DO_CURVEBALL_TLS_UNI_HTTP=0
+DO_CURVEBALL_TLS_UNI_HTTPS=0
+
+for testcase in $* ; do 
+    case "$testcase" in
+	1|normal-http)
+	    DO_NORMAL_HTTP=1
+	    ;;
+	2|normal-https)
+	    DO_NORMAL_HTTPS=1
+	    ;;
+	3|curveball-http-http)
+	    DO_CURVEBALL_HTTP_HTTP=1
+	    ;;
+	4|curveball-http-https)
+	    DO_CURVEBALL_HTTP_HTTPS=1
+	    ;;
+	5|curveball-https-http)
+	    DO_CURVEBALL_HTTPS_HTTP=1
+	    ;;
+	6|curveball-https-https)
+	    DO_CURVEBALL_HTTPS_HTTPS=1
+	    ;;
+	7|curveball-http-uni-http)
+	    DO_CURVEBALL_HTTP_UNI_HTTP=1
+	    ;;
+	8|curveball-http-uni-https)
+	    DO_CURVEBALL_HTTP_UNI_HTTPS=1
+	    ;;
+	9|curveball-tls-uni-http)
+	    DO_CURVEBALL_TLS_UNI_HTTP=1
+	    ;;
+	10|curveball-tls-uni-https)
+	    DO_CURVEBALL_TLS_UNI_HTTPS=1
+	    ;;
+	0|all)
+	    DO_NORMAL_HTTP=1
+	    DO_NORMAL_HTTPS=1
+	    DO_CURVEBALL_HTTP_HTTP=1
+	    DO_CURVEBALL_HTTP_HTTPS=1
+	    DO_CURVEBALL_HTTPS_HTTP=1
+	    DO_CURVEBALL_HTTPS_HTTPS=1
+	    DO_CURVEBALL_HTTP_UNI_HTTP=1
+	    DO_CURVEBALL_HTTP_UNI_HTTPS=1
+	    DO_CURVEBALL_TLS_UNI_HTTP=1
+	    DO_CURVEBALL_TLS_UNI_HTTPS=1
+	    ;;
+	-h|help)
+	    usage
+	    exit 0
+	    ;;
+	*)
+	    echo "$0: Error: Unknown test condition $testcase"
+	    usage
+	    exit 1
+	    ;;
+    esac
+done
+
 # Get sudo established quickly, instead of making the user
 # type a password later
 ${SUDO} /bin/true
 
-condition="normal http download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+if [ 0 -ne ${DO_NORMAL_HTTP} ]; then
+    condition="normal http download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    "http://${COVERT}/?size=$TSIZE"
-done
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		"http://${COVERT}/?size=$TSIZE"
+    done
+fi
 
-condition="normal https download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+if [ 0 -ne ${DO_NORMAL_HTTPS} ]; then
+    condition="normal https download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    "https://${COVERT}/?size=$TSIZE"
-done
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		"https://${COVERT}/?size=$TSIZE"
+    done
+fi
 
-# If there's already a curveball client running, then we don't know
-# what parameters it has: kill it and start a new one.
-#
-${SUDO} ${PKILL} -f ${CLIENT}
-${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w 2> /dev/null &
-sleep 5
+if [ 0 -ne ${DO_CURVEBALL_HTTP_HTTP} ]; then
+    # Kill the current client, if any, and rerun with the http client
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w 2> /dev/null &
+    sleep 5
 
-condition="curveball-http http download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+    condition="curveball-http http download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    --socks localhost:5010 \
-	    "http://$COVERT/?size=$TSIZE"
-done
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		--socks localhost:5010 \
+		"http://$COVERT/?size=$TSIZE"
+    done
+fi
 
-condition="curveball-http https download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+if [ 0 -ne ${DO_CURVEBALL_HTTP_HTTPS} ]; then
+    # Kill the current client, if any, and rerun with the http client
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w 2> /dev/null &
+    sleep 5
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    --socks localhost:5010\
-	    "https://$COVERT/?size=$TSIZE"
-done
+    condition="curveball-http https download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-# Kill the http client and rerun with the https client
-#
-${SUDO} ${PKILL} -f ${CLIENT}
-${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" 2> /dev/null &
-sleep 5
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		--socks localhost:5010\
+		"https://$COVERT/?size=$TSIZE"
+    done
+fi
 
-condition="curveball-https http download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+if [ 0 -ne ${DO_CURVEBALL_HTTPS_HTTP} ]; then
+    # Kill the current client, if any, and rerun with the https client
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" 2> /dev/null &
+    sleep 5
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    --socks localhost:5010 \
-	    "http://$COVERT/?size=$TSIZE"
-done
+    condition="curveball-https http download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-condition="curveball-https https download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		--socks localhost:5010 \
+		"http://$COVERT/?size=$TSIZE"
+    done
+fi
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    --socks localhost:5010\
-	    "https://$COVERT/?size=$TSIZE"
-done
+if [ 0 -ne ${DO_CURVEBALL_HTTPS_HTTPS} ]; then
+    # Kill the current client, if any, and rerun with the https client
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" 2> /dev/null &
+    sleep 5
 
-# Kill the https client and rerun with the http-uni client
-#
+    condition="curveball-https https download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-# TODO: use the same TSIZE for http-uni.
-# The http-uni client is much slower than the others, so cut the
-# transfer size so we don't have to wait forever.
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		--socks localhost:5010\
+		"https://$COVERT/?size=$TSIZE"
+    done
+fi
 
-TSIZE=$((TSIZE / 40))
+if [ 0 -ne ${DO_CURVEBALL_HTTP_UNI_HTTP} ]; then
+    # Kill the current client, if any, and rerun with the http-uni client
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w -u 2> /dev/null &
+    sleep 5
 
-${SUDO} ${PKILL} -f ${CLIENT}
-${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w -u 2> /dev/null &
-sleep 5
+    condition="curveball-http-uni http download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-condition="curveball-httpu http download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		--socks localhost:5010 \
+		"http://$COVERT/?size=$SMALL_TSIZE"
+	# The unidirectional tunnel works better if there is a small gap
+	# between large requests.
+	sleep 4
+    done
+fi
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    --socks localhost:5010 \
-	    "http://$COVERT/?size=$TSIZE"
-    # The unidirectional tunnel works better if there is a small gap
-    # between large requests.
-    sleep 4
-done
+if [ 0 -ne ${DO_CURVEBALL_HTTP_UNI_HTTPS} ]; then
+    # Kill the current client, if any, and rerun with the http-uni client
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:80" -w -u 2> /dev/null &
+    sleep 5
 
-condition="curveball-httpu https download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+    condition="curveball-http-uni https download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    --socks localhost:5010\
-	    "https://$COVERT/?size=$TSIZE"
-    # The unidirectional tunnel works better if there is a small gap
-    # between large requests.
-    sleep 4
-done
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		--socks localhost:5010\
+		"https://$COVERT/?size=$SMALL_TSIZE"
+	# The unidirectional tunnel works better if there is a small gap
+	# between large requests.
+	sleep 4
+    done
+fi
 
-# Kill the httpu client and rerun with the httpsu client
-#
-${SUDO} ${PKILL} -f ${CLIENT}
-${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" -u 2> /dev/null &
-sleep 5
+if [ 0 -ne ${DO_CURVEBALL_TLS_UNI_HTTP} ]; then
+    # Kill the current client, if any, and rerun with the tls-uni client
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" -u 2> /dev/null &
+    sleep 5
 
-condition="curveball-httpsu http download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+    condition="curveball-tls-uni http download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    --socks localhost:5010 \
-	    "http://$COVERT/?size=$TSIZE"
-done
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		--socks localhost:5010 \
+		"http://$COVERT/?size=$SMALL_TSIZE"
+	sleep 10
+    done
+fi
 
-condition="curveball-httpsu https download"
-iter=0
-while [ $iter -lt $ITERS ]; do
-    iter=$((iter + 1))
+if [ 0 -ne ${DO_CURVEBALL_TLS_UNI_HTTPS} ]; then
+    # Kill the current client, if any, and rerun with the tls-uni client
+    #
+    ${SUDO} ${PKILL} -f ${CLIENT}
+    ${SUDO} ${CLIENTPATH} -x -d "${DECOY}:443" -u 2> /dev/null &
+    sleep 5
 
-    $CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
-	    -4 -o /dev/null -s \
-	    --socks localhost:5010\
-	    "https://$COVERT/?size=$TSIZE"
-done
+    condition="curveball-tls-uni https download"
+    echo $condition
+    iter=0
+    while [ $iter -lt $ITERS ]; do
+	iter=$((iter + 1))
 
-
+	$CURL -w "$condition $iter %{speed_download} B/s %{size_download} B\n" \
+		-4 -o /dev/null -s \
+		--socks localhost:5010\
+		"https://$COVERT/?size=$SMALL_TSIZE"
+	sleep 10
+    done
+fi
 
 # Clean up any clients we left behind
 #
